spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        healthCheckPath: ${server.contextPath}/health
        healthCheckInterval: 3s
        instanceId: ${spring.application.name}:${HOSTNAME:${random.value}}
      config:
        failFast: true
