spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        healthCheckPath: ${server.contextPath}/health
        healthCheckInterval: 3s
        instanceId: ${spring.application.instance_id:${HOSTNAME:${spring.application.name}}}
      config:
        failFast: true
